{% set name = "backports.entry-points-selectable" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports.entry_points_selectable-{{ version }}.tar.gz
  sha256: 17a8b44ae700fba548686dd274ddc91c060371565cd63806c20a1d33911746e6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >=3.8
    - importlib-metadata

test:
  imports:
    - backports.entry_points_selectable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/backports.entry_points_selectable
  summary: Compatibility shim providing selectable entry points for older implementations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sergiopasra
